dist: trusty
notifications:
  email: false

language: rust
rust:
  - 1.18.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - nightly
cache:
  cargo: true
  directories:
    - front/node_modules

addons:
  postgresql: "9.5"
  apt:
    packages:
      - curl
      - libpq-dev
      - phantomjs
      - pkg-config

before_install:
  - nvm install 6
  - npm config set spin false
  - npm install -g phantomjs-prebuilt yarn
  - phantomjs --version
install:
  - cd front/
  - yarn install
  - cd ../
  - cargo install --force diesel_cli

before_script:
  - source ./vagrant/vagrant_env.sh
  - export DATABASE_URL='postgres://localhost/dashboard'
  - unset CARGO_TARGET_DIR

  - diesel setup
  - diesel migration run

script:
  - cargo build --verbose
  - cargo test --verbose
  - cd front && ember build
