dist: trusty
notifications:
  email: false
language: rust
rust:
  # sync in `rust-toolchain` file
  - nightly-2019-04-26
cache:
  directories:
    - "$HOME/.cargo"
# But don't cache the cargo registry
before_cache:
  - rm -rf "$HOME/.cargo/registry"
addons:
  postgresql: '9.5'
  apt:
    packages:
    - curl
    - libpq-dev
    - pkg-config
before_install:
  - rustup component add rustfmt
  - cargo fmt --all -- --check
install:
  - export RUST_LOG=debug,hyper=info,rustc=error,cargo=error,jobserver=error
  - export GITHUB_WEBHOOK_SECRETS=none
  - export GITHUB_ACCESS_TOKEN=
  - export GITHUB_SCRAPE_INTERVAL=6000
  - export GITHUB_USER_AGENT=none-agent-with-left-beef
  - export POST_COMMENTS=false
  - export RUST_BACKTRACE=1
  - export PATH=$PATH:$HOME/.cargo/bin
  - export DATABASE_URL=postgres://localhost/dashboard
  - export DATABASE_POOL_SIZE=5
  - rustup default $(cat rust-toolchain)
  - cargo install cargo-update || true
  - cargo install-update-config diesel_cli --default-features false --feature postgres
  - cargo install-update -i diesel_cli
before_script:
  - diesel setup
  - diesel migration run
  - psql -q -d $DATABASE_URL < githubuser-backup.pg
script:
  - cargo build
  - cargo test
before_deploy:
  - DATABASE_URL=$(heroku config:get DATABASE_URL -a rfcbot-rs) diesel migration run
deploy:
  - provider: heroku
    api_key:
      secure: "HgoF2n6pnzUhZ4oBNRo3gSoxj/o9x7QW0fKaj9sEYDNkTgak9IX3ha0antoYKB7dMw7IvB8oqVAHqldlGlG/kxUDKN8kaYA4O7CZgKP0auykTkmH61FP7MKV0hV0vyFfJLSraClVw/DL5tjYybs/rSBWFAvwttIB7QlcFv5sLIuwe5nHzftFfxba0H1+0oynO55FlmRzFBWydlFVNTsGVRddFHPgG3f2V9YYIjT18MKvn+BcV7WUq6QweB/3RjwTDYzws9mcWt6i3ju1D4nDTDVbtzeLs7Yt+NhnvrDeB+2FWSrV03LCjnnzv2zCUaROU522Vns0ZC/+2b9V3YbcCBJRA8QLBdo12JUCUzrdk8DOqIYKwlW6WbI3DcgRGz9Li7Dw2466+lsPidBfcdxnziTvc+r/2r6dKv3q7nwDpoZEyxnnTumPf50PJZs/lDu99Vo5C2NIdN2O5sqDHd8AJTLtWrY3FdN5MGKqTm0R9rVnObvUkTKbZJrDn39O5MU3mnHINUT+6ZCnNgra7rNn7Ai3tA1RKPB7kIZo41Td8j56iSLANXziCh0MikPfQv4x1scl3c1h5bR8ZqxVqH4IODjDJrJv43+hsbE9xGsmrC4OaqImLUpl/8zi6a4zZ8Na1AiFKVcdLZ9xt40/2yg7ysn53SCpQ5vty/j36clNwAE="
