[package]
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
name = "rust-dashboard"
version = "0.1.0"

[dependencies]
clap = "2.2.5"
crossbeam = "0.2.9"
dotenv = "0.9.0"
env_logger = "0.4"
hex = "0.2.0"
hyper = "0.10.0"
hyper-native-tls = "0.2.1"
iron = "0.5.0"
lazy_static = "0.2.0"
log = "0.3.6"
mount = "0.3.0"
r2d2 = "0.7.1"
r2d2-diesel = "0.13"
router = "0.5.0"
rust-crypto = "0.2.36"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
urlencoded = "0.5"

[dependencies.chrono]
features = ["serde"]
version = "0.3.1"

[dependencies.diesel]
default-features = false
features = ["postgres", "chrono", "large-tables"]
version = "0.13"

[dependencies.diesel_codegen]
default-features = false
features = ["dotenv", "postgres"]
version = "0.13"
