[fcp_behaviors]

[fcp_behaviors."rust-lang/rfcs"]
close = true
postpone = true

[fcp_behaviors."rust-lang/rust"]
close = false
postpone = false

[teams]
url = "https://team-api.infra.rust-lang.org/v1/rfcbot.json"
